# Site wide configuration

title:            Sapphire Development Blog
locale:           en_US
url:              http://appliedtelekinetics.com/sapphire-blog
baseurl:          /sapphire-blog

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: SapphirePowered.com
  web: http://SapphirePowered.com
  avatar: hero.jpg
  bio: "This is where updates, news and other Sapphire-related stuff will be posted."
  email: info@sapphirepowered.com
  disqus-shortname: appliedtelekineticsdevelopmentblog
  twitter: SapphirePowered
  facebook: SapphirePowered
  google:
    plus: SapphirePowered
    analytics: UA-64686658-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: AppliedTelekinetics
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: xunker
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
